name: Test successful build of cpsi-mapview

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache Node.js modules 💾
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies ⏬
      run: npm install

    - name: Build turf.js
      run: npm run build:turf

    - name: Testing 🔎
      run: npm test

    - name: Generate coverage 🧪
      run: npm run test:coverage

    - name: Publish to coveralls ⭐
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
