name: Build and publish application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install needed Java version
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Node.js modules 💾
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Cache ext 💾
      uses: actions/cache@v4
      with:
        path: |
          resources/external
          ext-7.0.0
          ext-7.0.0-gpl.zip
          sencha-cmd-download
          sencha-cmd
        key: ${{ runner.OS }}-node-${{ hashFiles('resources/external/ext-all.js') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Download ExtJS, install sencha cmd
      run: |
        if (test ! -f ext-7.0.0-gpl.zip); then wget -q http://cdn.sencha.com/ext/gpl/ext-7.0.0-gpl.zip -O ext-7.0.0-gpl.zip; fi
        if (test ! -d ext-7.0.0); then unzip -qo ext-7.0.0-gpl.zip; fi
        mkdir -p sencha-cmd-download
        if (test ! -f sencha-cmd-download/SenchaCmd-7.2.0.84-linux-amd64.sh.zip); then wget -q  https://cdn.sencha.com/cmd/7.2.0.84/no-jre/SenchaCmd-7.2.0.84-linux-amd64.sh.zip -O sencha-cmd-download/SenchaCmd-7.2.0.84-linux-amd64.sh.zip; fi
        if (test ! -f sencha-cmd-download/SenchaCmd-7.2.0.84-linux-amd64.sh); then unzip -q -d sencha-cmd-download sencha-cmd-download/SenchaCmd-7.2.0.84-linux-amd64.sh.zip; fi
        mkdir -p sencha-cmd
        if (test ! -f sencha-cmd/sencha); then ./sencha-cmd-download/SenchaCmd-7.2.0.84-linux-amd64.sh -q -dir "$PWD/sencha-cmd"; fi
        mv ext-7.0.0 ext

    - name: Install dependencies ⏬
      run: npm install

    - name: Build turf.js
      run: npm run build:turf

    - name: Testing 🔎
      run: npm test

    - name: Generate coverage 🧪
      run: npm run test:coverage

    - name: Publish to coveralls ⭐
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build sencha app
      run: |
        SENCHACMD="$PWD/sencha-cmd/sencha"
        $SENCHACMD app build

    - name: Cleanup and prepare pages
      run: |
        mkdir -p docs
        npm run generate:docs
        cp -r docs build/production/CpsiMapview/docs

    - name: Copy presentation to output folder and prepare pages
      run: |
        cp -r presentation build/production/CpsiMapview/presentation

    - name: Deploy gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/production/CpsiMapview
        destination_dir: .
